# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentGatewayStub(object):
    """🔹 Payment Gateway Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/payment.PaymentGateway/RegisterClient',
                request_serializer=payment__pb2.ClientInfo.SerializeToString,
                response_deserializer=payment__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.AuthenticateClient = channel.unary_unary(
                '/payment.PaymentGateway/AuthenticateClient',
                request_serializer=payment__pb2.UserCredentials.SerializeToString,
                response_deserializer=payment__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GenerateTransactionID = channel.unary_unary(
                '/payment.PaymentGateway/GenerateTransactionID',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=payment__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/payment.PaymentGateway/ProcessPayment',
                request_serializer=payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=payment__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.ViewBalance = channel.unary_unary(
                '/payment.PaymentGateway/ViewBalance',
                request_serializer=payment__pb2.BalanceRequest.SerializeToString,
                response_deserializer=payment__pb2.BalanceResponse.FromString,
                _registered_method=True)


class PaymentGatewayServicer(object):
    """🔹 Payment Gateway Service
    """

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTransactionID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=payment__pb2.ClientInfo.FromString,
                    response_serializer=payment__pb2.RegisterResponse.SerializeToString,
            ),
            'AuthenticateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateClient,
                    request_deserializer=payment__pb2.UserCredentials.FromString,
                    response_serializer=payment__pb2.AuthResponse.SerializeToString,
            ),
            'GenerateTransactionID': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTransactionID,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=payment__pb2.TransactionResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=payment__pb2.PaymentRequest.FromString,
                    response_serializer=payment__pb2.PaymentResponse.SerializeToString,
            ),
            'ViewBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewBalance,
                    request_deserializer=payment__pb2.BalanceRequest.FromString,
                    response_serializer=payment__pb2.BalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentGateway(object):
    """🔹 Payment Gateway Service
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/RegisterClient',
            payment__pb2.ClientInfo.SerializeToString,
            payment__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/AuthenticateClient',
            payment__pb2.UserCredentials.SerializeToString,
            payment__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTransactionID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/GenerateTransactionID',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            payment__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/ProcessPayment',
            payment__pb2.PaymentRequest.SerializeToString,
            payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/ViewBalance',
            payment__pb2.BalanceRequest.SerializeToString,
            payment__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BankServiceStub(object):
    """🔹 Bank Service for Interbank Transfers with 2PC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InterbankTransfer = channel.unary_unary(
                '/payment.BankService/InterbankTransfer',
                request_serializer=payment__pb2.BankTransferRequest.SerializeToString,
                response_deserializer=payment__pb2.BankTransferResponse.FromString,
                _registered_method=True)
        self.PrepareTransaction = channel.unary_unary(
                '/payment.BankService/PrepareTransaction',
                request_serializer=payment__pb2.PrepareRequest.SerializeToString,
                response_deserializer=payment__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/payment.BankService/CommitTransaction',
                request_serializer=payment__pb2.CommitRequest.SerializeToString,
                response_deserializer=payment__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.AbortTransaction = channel.unary_unary(
                '/payment.BankService/AbortTransaction',
                request_serializer=payment__pb2.AbortRequest.SerializeToString,
                response_deserializer=payment__pb2.AbortResponse.FromString,
                _registered_method=True)


class BankServiceServicer(object):
    """🔹 Bank Service for Interbank Transfers with 2PC
    """

    def InterbankTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareTransaction(self, request, context):
        """✅ Phase 1: Prepare
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """✅ Phase 2: Commit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortTransaction(self, request, context):
        """✅ Rollback
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InterbankTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.InterbankTransfer,
                    request_deserializer=payment__pb2.BankTransferRequest.FromString,
                    response_serializer=payment__pb2.BankTransferResponse.SerializeToString,
            ),
            'PrepareTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareTransaction,
                    request_deserializer=payment__pb2.PrepareRequest.FromString,
                    response_serializer=payment__pb2.PrepareResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=payment__pb2.CommitRequest.FromString,
                    response_serializer=payment__pb2.CommitResponse.SerializeToString,
            ),
            'AbortTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortTransaction,
                    request_deserializer=payment__pb2.AbortRequest.FromString,
                    response_serializer=payment__pb2.AbortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.BankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.BankService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BankService(object):
    """🔹 Bank Service for Interbank Transfers with 2PC
    """

    @staticmethod
    def InterbankTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/InterbankTransfer',
            payment__pb2.BankTransferRequest.SerializeToString,
            payment__pb2.BankTransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/PrepareTransaction',
            payment__pb2.PrepareRequest.SerializeToString,
            payment__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/CommitTransaction',
            payment__pb2.CommitRequest.SerializeToString,
            payment__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/AbortTransaction',
            payment__pb2.AbortRequest.SerializeToString,
            payment__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
